### ISSUE TITLE
Add some better animation for the mask 

### ISSUE THREAD

**Issue by Suman373** [Suman373/Ironmask#2]
Use css for styling the background, or the mask.
Add some sleek and modern animation ( don't worry, if you are beginner, try to use creativity)
Make sure to run it properly on your local machine, take some snapshots.
Post the snapshots along with the PR  you will make.

**Comment by abitsalihu** [comment]
@Suman373 Hey, I would like to give it a go at this.

**Comment by ujjawalD07** [comment]
@Suman373 Hey, I am a beginner full-stack developer, this is my first try at open source contribution. I'd like to start it off with this issue.

**Comment by Suman373** [comment]
> @Suman373 Hey, I would like to give it a go at this.

Yea! Go ahead.

**Comment by Suman373** [comment]
> @Suman373 Hey, I am a beginner full-stack developer, this is my first try at open source contribution. I'd like to start it off with this issue.

Sure ! Good luck!
